---
log_level: debug-color
introspection_addr: ""
http_listen_addr: ":6000"
updaters: {}
indexer:
  connstring: "postgresql://clair:UJo3PW1j0uU@quay-pgsql/clair?sslmode=disable"
  scanlock_retry: 10
  layer_scan_concurrency: 5
  migrations: true
matcher:
  connstring: "postgresql://clair:UJo3PW1j0uU@quay-pgsql/clair?sslmode=disable"
  max_conn_pool: 100
  migrations: true
notifier:
  connstring: "postgresql://clair:UJo3PW1j0uU@quay-pgsql/clair?sslmode=disable"
  migrations: true
  delivery_interval: 5s
  poll_interval: 15s
  webhook:
    target: "http://quay:8080/secscan/notification"
    callback: "http://quay-clair:6000/notifier/api/v1/notification"
metrics:
  name: "prometheus"
