CREATE EXTENSION pg_trgm WITH SCHEMA pg_catalog;

CREATE ROLE quay WITH LOGIN ENCRYPTED PASSWORD 'Yhh1Pq0Dh1j';
CREATE DATABASE quay WITH OWNER 'quay';

CREATE ROLE clair WITH LOGIN ENCRYPTED PASSWORD 'UJo3PW1j0uU';
CREATE DATABASE clair WITH OWNER 'clair';
